---
dist: xenial
sudo: false
cache:
  - bundler
  - directories:
    - /home/travis/.rvm/
language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-9.2.7.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.7.0

before_install: gem update --system -N

install:
  - bundle install --retry 3

script: ./test/run_tests.sh
